name: Docker Image Linly-Talker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag dynamoowusu/linly-talker:${{ github.sha }}
    
 
